### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by dimik** [dfilatov/vow-queue#16]
Clone repository
run "npm install"
run "npm test"

`
> vow-queue@0.4.2 test /Users/dmk/Work/vow-queue
> make validate

./node_modules/.bin/jshint .
./node_modules/.bin/jscs .
/Users/dmk/Work/vow-queue/node_modules/vow-fs/lib/fs.js:152
            var promise = Vow.promise();
                              ^

TypeError: Vow.promise is not a function
    at Object.exists (/Users/dmk/Work/vow-queue/node_modules/vow-fs/lib/fs.js:152:31)
    at Object.checkPath (/Users/dmk/Work/vow-queue/node_modules/jscs/lib/checker.js:204:22)
    at /Users/dmk/Work/vow-queue/node_modules/jscs/lib/cli.js:39:28
    at Array.map (native)
    at Object.<anonymous> (/Users/dmk/Work/vow-queue/node_modules/jscs/lib/cli.js:38:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
make: *** [lint] Error 1
npm ERR! Test failed.  See above for more details.
`

**Comment by dimik** [comment]
Seems like that happened because of JSCS
